# Generated by Django 3.2 on 2022-02-05 20:02

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=36, validators=[blog.validators.validate_title_length])),
                ('caption', models.TextField(validators=[blog.validators.validate_caption_length])),
            ],
        ),
    ]
